const fs = require('fs');
const assert = require('assert');
const html = fs.readFileSync('index.html', 'utf8');
const app = fs.readFileSync('src/app.js', 'utf8');
function ok(condition, message) { assert.ok(condition, message); console.log(`✓ ${message}`); }
ok(html.includes('v0.7.10'), 'index displays v0.7.10');
ok(html.includes('id="posterConcurrent"'), 'settings exposes concurrent screenshot control');
ok(html.includes('max="63"'), 'concurrency control supports up to 63 workers');
ok(html.includes('id="onboardingConcurrent"'), 'onboarding exposes first-use concurrency setup');
ok(html.includes('data-icon'), 'UI uses local SVG icon hooks');
ok(html.includes('id="captureSize"'), 'settings exposes screenshot viewport control');
ok(html.includes('id="cropMode"'), 'settings exposes poster crop mode control');
ok(html.includes('id="whitePageEnhance"'), 'settings exposes white-page poster enhancement');
ok(app.includes('function posterizeScreenshot'), 'app includes posterization pipeline');
ok(app.includes('MAX_SCREENSHOT_CONCURRENCY = 63'), 'app defines 1-63 screenshot concurrency guard');
ok(app.includes('function iconSvg'), 'app includes built-in local icon renderer');
ok(app.includes('ScreenshotProgress') || app.includes('并发'), 'app includes concurrent screenshot progress wording');

ok(html.includes('id="onboardingExportHtml"'), 'onboarding exposes quick HTML bookmark export');
ok(html.includes('id="exportBookmarksHtmlBtn"'), 'data settings expose all-bookmarks HTML export');
ok(html.includes('id="requireBackupBeforeOrganize"'), 'settings expose safety backup reminder switch');
ok(app.includes('buildBookmarksHtml'), 'app can build browser-importable bookmarks HTML backup');
ok(app.includes('ensureSafetyBackupBeforeOrganize'), 'app warns before destructive bookmark operations if no backup exists');
ok(!app.includes('Math.min(24'), 'poster generation no longer has a hard-coded 24-item cap');
ok(app.includes('THUMBNAIL_SCHEMA_VERSION'), 'app migrates old thumbnail cache after poster crop fixes');
ok(app.includes('ultra-thin') || app.includes('strip'), 'app documents and guards against strip-like poster crops');
ok(app.includes('inspectPosterImageQuality'), 'app rejects strip-like screenshots before saving cache');
ok(app.includes('createDesignedFallbackPoster'), 'app creates designed local poster fallback for invalid screenshots');
ok(app.includes('drawFallbackBrowserShell'), 'fallback poster uses reference-style browser shell');
ok(app.includes('drawFallbackStatusBand'), 'fallback poster includes polished local-cover status band');
ok(app.includes('fallbackPosterTheme'), 'fallback poster uses deterministic design themes');
ok(app.includes("poster-local-design-v7"), 'app bumps thumbnail schema to purge old strip caches and old fallback cards');
ok(!app.includes("source: 'favicon'"), 'fallback poster never stores favicon-only posters as final covers');
console.log('UI config tests passed.');
const css = fs.readFileSync('src/styles.css', 'utf8');
ok(css.includes('--shot-h:160px') && css.includes('--body-h:46px'), 'CSS includes strict poster card geometry lock');
ok(css.includes('aspect-ratio:16/9'), 'poster cover uses fixed 16:9 aspect ratio');
ok(css.includes('text-overflow:ellipsis') && css.includes('white-space:nowrap'), 'bookmark titles are kept inside card bounds');
ok(css.includes('repeat(auto-fill,minmax(var(--card-w),1fr))'), 'large poster grid uses fixed reference card tracks');
ok(css.includes('--card-w:210px'), 'mobile poster grid prevents horizontal overflow');

ok(app.includes('posterConsentGranted'), 'poster generation requires explicit onboarding consent');
ok(app.includes('if (this.hasPosterGenerationConsent())') && app.includes("setTimeout(() => this.kickoffAutoPosters('initial'), 900);"), 'initial auto poster generation is gated by explicit consent');
ok(app.includes('shouldGateInitialBookmarkRead'), 'first run gates bookmark tree reading behind onboarding');
ok(app.includes('renderLockedState'), 'first run renders a safe locked state before reading bookmarks');
ok(app.includes('finishOnboardingFlow'), 'onboarding acknowledgement explicitly loads bookmarks after user action');
ok(html.includes('onboardingAutoPosterConsent'), 'onboarding includes explicit screenshot consent checkbox');
ok(html.includes('点击“开始生成真实海报”后才会访问网页'), 'onboarding explains screenshot only starts after confirmation');
ok(html.includes('id="posterConcurrentNumber"'), 'settings exposes precise numeric concurrency input');
ok(html.includes('id="onboardingConcurrentNumber"'), 'onboarding exposes precise numeric concurrency input');
ok(html.includes('id="posterAspectSelect"'), 'toolbar exposes landscape/portrait poster switch');
ok(html.includes('id="languageSelect"') && html.includes('id="settingsLanguageSelect"'), 'UI exposes Chinese/English language controls');
ok(app.includes("language: 'zh-CN'"), 'default UI language is Chinese');
ok(html.includes('id="saveAndRunAiBtn"'), 'AI settings include a clear save-and-start action');
ok(css.includes('.onboarding-columns') && css.includes('repeat(3,minmax(0,1fr))'), 'onboarding has the new three-column reference layout style');
ok(css.includes('--body-h:46px'), 'large poster card uses compact fixed height');

// Onboarding must use real raster preview images, not synthetic placeholder posters.
ok(html.includes('assets/onboarding/mdn.png'), 'onboarding uses real MDN preview image');
ok(html.includes('assets/onboarding/github.png'), 'onboarding uses real GitHub preview image');
ok(html.includes('assets/onboarding/vue.png'), 'onboarding uses real Vue preview image');
ok(!html.includes('mini-poster dark'), 'onboarding no longer uses synthetic mini-poster placeholders');

ok(app.includes('renderLocalCover'), 'homepage uses lightweight local covers before screenshot consent');
ok(app.includes('siteFaviconUrl'), 'homepage tries real site favicon before local fallback icons');
ok(app.includes('localBookmarkIconDataUri'), 'homepage keeps local data-URI icon fallback');
ok(app.includes('bundledPreviewForBookmark'), 'homepage can show bundled real preview images without network access');
ok(app.includes('posterAspectClass'), 'app renders selectable landscape/portrait poster classes');
ok(css.includes('poster-portrait') && css.includes('aspect-ratio:2/3'), 'CSS supports portrait poster cards');
ok(app.includes('captureViewportProfile') && app.includes('mobile: true') && app.includes('portrait ? 720 : 360'), 'portrait posters use mobile capture profile and movie poster output');
ok(app.includes('const I18N'), 'app includes lightweight Chinese/English UI text map');
ok(css.includes('.thumbnail-guide') && css.includes('.bulk-bar'), 'CSS includes homepage stability fixes');
ok(html.includes('styles.css?v=0.7.21'), 'HTML busts stylesheet cache for latest poster layout');
ok(css.includes('.poster-shot.local-cover') && css.includes('.mock-browser'), 'CSS includes latest poster dominance refinement');
ok(css.includes('--shot-h:160px'), 'large landscape poster allocates more height to screenshots');
ok(css.includes('--body-h:46px'), 'large landscape poster keeps the title footer compact');
ok(html.includes('src/app.js?v=0.7.21'), 'HTML busts app script cache for latest interactions');
ok(html.includes('settings-overview-card'), 'settings basic tab includes overview quick-start card');
ok(html.includes('data-jump-tab="ai"') && app.includes('data-jump-tab'), 'settings can jump directly to AI setup/start flow');
ok(html.includes('class="primary ai-start-action"') && html.includes('data-proxy="saveAndRunAiBtn"'), 'AI settings show a first-screen save-and-run action');
ok(css.includes('.settings-dock') && css.includes('.settings-status-strip'), 'CSS includes latest settings refinement');
ok(css.includes('@media(max-width:820px)'), 'CSS includes final mobile and status strip polish');
ok(css.includes('.settings-card') && css.includes('grid-template-columns:1fr'), 'mobile poster grid uses a single stable column');
ok(css.includes('.onboarding-columns') && css.includes('repeat(3,minmax(0,1fr))'), 'mobile toolbar uses compact three-column controls');
ok(css.includes('aspect-ratio:16/9'), 'mobile landscape posters keep real screenshot aspect ratio');
ok(html.includes('settings-status-strip') && html.includes('settings-dock'), 'settings pages expose summary strips and sticky action dock');
ok(app.includes('renderSettingsHeader') && app.includes('handleSettingsDockPrimary'), 'settings dock actions change by active tab');
ok(css.includes('.bp-setting-card') && css.includes('.bp-choice-card'), 'CSS includes settings operation and visual refinement pass');
ok(css.includes('.setting-hero-card') && css.includes('.security-card'), 'CSS includes restrained settings surfaces and readable card footers');
ok(app.includes('class="card-head"') && css.includes('.card-head .select-dot'), 'poster card controls are integrated into the info area');
ok(css.includes('grid-template-columns:minmax(0,1fr)') && css.includes('.folder-tag'), 'poster card folder row uses the full metadata width');
ok(app.includes('enhanceToolbarSelects') && css.includes('.custom-select-menu'), 'toolbar select menus use styled custom dropdowns');
ok(css.includes('.folder-indent{display:none}') && css.includes('grid-template-columns:22px minmax(0,1fr) auto'), 'folder tree keeps icon title and count aligned');
ok(css.includes('z-index:120') && css.includes('box-shadow:0 14px 34px'), 'expanded search floats above toolbar controls');
ok(css.includes('poster-selected-wash') && css.includes('poster-shot-flash') && css.includes('.poster-card.selected .card-body'), 'selected posters have persistent visual effects');
ok(app.includes('activeCaptureWindows') && app.includes('activeCaptureTabs'), 'app tracks all temporary screenshot windows and tabs');
ok(app.includes('cleanupActiveCaptureSurfaces') && app.includes('stopPosterGeneration'), 'stop poster generation closes tracked screenshot surfaces');
ok(app.includes('chrome.tabs.onRemoved') && app.includes('removedListener'), 'tab-load wait exits when temporary screenshot tabs are closed');
ok(app.includes('CAPTURE_TAB_GROUP_TITLE') && app.includes('ensureCaptureTabWorkspace'), 'screenshot tabs are collected into a named tab group workspace');
ok(app.includes("if (strategy === 'active-tabs') return 1"), 'foreground active-tab screenshots run one tab at a time');
